apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant2-app
  namespace: argocd
spec:
  project: tenant2-project
  source:
    repoURL: git@github.com:abhinav-dops/multi-tenant-gitops-platform.git
    targetRevision: main
    path: helm/tenant-app
    helm:
      valueFiles:
        - ../../helm/values/tenant2-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: tenant2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
